version: '3.8'

services:

  prometheus:
    image: prom/prometheus:v2.30.3
    restart: unless-stopped
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.2.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/config
      - alertmanager-data:/data
    command:
      - --config.file=/config/alertmanager.yml
      - --log.level=debug

  loki:
    image: grafana/loki:2.4.2
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki-data:/data
      - ./loki:/etc/loki

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox:/etc/blackbox
      - blackbox-data:/data
    command:
      - --config.file=/etc/blackbox/blackbox.yml

  grafana-oncall:
    image: grafana/oncall:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - oncall-data:/var/lib/oncall
    environment:
      BASE_URL: http://localhost:8080
      SECRET_KEY: oncallsecret
      DATABASE_TYPE: sqlite3
      DATABASE_PATH: /var/lib/oncall/oncall.db
      BROKER_TYPE: redis
      REDIS_URI: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  loki-data:
  promtail-data:
  blackbox-data:
  oncall-data:
  redis-data:
